language: go

go:
  - 1.5
  - 1.6
  - tip

script: make getdeps test build

before_deploy:
  - ls
  - sudo apt-get -y install zip
  - zip -r bancho-x64.zip gobuild.exe -r

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file:
  - bancho-x64.zip
  skip_cleanup: true
